# Generated by Django 4.0.4 on 2022-05-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_song_duration'),
        ('playlists', '0002_alter_playlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='songs.song'),
        ),
    ]
