# Generated by Django 4.0.4 on 2022-05-12 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_song_duration'),
        ('playlists', '0004_remove_playlist_songs_playlistsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='songs.song'),
        ),
    ]
