# Generated by Django 4.0.4 on 2022-06-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0006_playlist_cover_alter_playlistsong_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
