# Generated by Django 4.0.4 on 2022-06-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0007_playlist_public_alter_playlist_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='name',
            new_name='title',
        ),
    ]
