# Generated by Django 4.0.4 on 2022-06-17 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_albumposition_album_alter_albumposition_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumposition',
            name='album',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='album_positions', to='albums.album'),
        ),
    ]
