# Generated by Django 4.0.4 on 2022-06-21 21:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_albumposition_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
