# Generated by Django 4.0.4 on 2022-06-21 21:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_song_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
